# Generated by Django 5.2.7 on 2025-11-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='supplier',
            name='suppliers_s_company_429547_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='suppliers_s_supplie_1452cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='suppliers_s_name_6277a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='suppliers_s_phone_af9b45_idx',
        ),
        migrations.AddField(
            model_name='supplier',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
