# Generated by Django 5.2.7 on 2026-01-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='product_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Products/Services'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shop/Business Name'),
        ),
    ]
