# Generated by Django 5.2.7 on 2025-10-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_rename_date_created_supplier_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='purchase_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
