# Generated by Django 5.2.7 on 2025-10-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
