# Generated by Django 5.2.7 on 2026-01-26 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('sales', 'Sales'), ('money_receipt', 'Money Receipt'), ('purchases', 'Purchases'), ('products', 'Products'), ('accounts', 'Accounts'), ('customers', 'Customers'), ('suppliers', 'Suppliers'), ('expense', 'Expense'), ('return', 'Return'), ('reports', 'Reports'), ('users', 'Users'), ('administration', 'Administration'), ('settings', 'Settings')], max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_create_pos', models.BooleanField(default=False)),
                ('can_create_short', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='staff_role',
        ),
        migrations.AddField(
            model_name='user',
            name='permission_source',
            field=models.CharField(choices=[('ROLE', 'Role Based'), ('CUSTOM', 'Custom'), ('MIXED', 'Mixed')], default='ROLE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['permission_source'], name='core_user_permiss_adf990_idx'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'module'], name='core_userpe_user_id_b64383_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['is_active'], name='core_userpe_is_acti_3eed93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'module')},
        ),
    ]
