# Generated by Django 5.2.7 on 2026-01-26 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userpermission_alter_rolepermission_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('sales', 'Sales'), ('money_receipt', 'Money Receipt'), ('purchases', 'Purchases'), ('products', 'Products'), ('accounts', 'Accounts'), ('customers', 'Customers'), ('suppliers', 'Suppliers'), ('expense', 'Expense'), ('return', 'Return'), ('reports', 'Reports'), ('users', 'Users'), ('administration', 'Administration'), ('settings', 'Settings')], max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.staffrole')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'unique_together': {('staff_role', 'module')},
            },
        ),
    ]
