# Generated by Django 5.2.7 on 2025-11-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_can_manage_customers_user_accounts_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_products',
            field=models.BooleanField(default=False),
        ),
    ]
