# Generated by Django 5.2.7 on 2026-01-16 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_can_manage_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fiscal_year_start',
            field=models.DateField(default=datetime.date(2026, 7, 1)),
        ),
    ]
