# Generated by Django 5.2.7 on 2025-11-14 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensehead',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='expensesubhead',
            options={'ordering': ['head__name', 'name']},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['account', 'expense_date'], name='expenses_ex_account_a6e3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='expensehead',
            index=models.Index(fields=['company', 'is_active'], name='expenses_ex_company_42b908_idx'),
        ),
        migrations.AddIndex(
            model_name='expensesubhead',
            index=models.Index(fields=['head', 'is_active'], name='expenses_ex_head_id_e796f5_idx'),
        ),
    ]
