# Generated by Django 6.0.2 on 2026-02-21 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensehead'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='subhead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensesubhead'),
        ),
    ]
