# Generated by Django 5.2.7 on 2025-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_description_expense_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensehead',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expensesubhead',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
