# Generated by Django 5.2.7 on 2026-01-25 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['company', 'purchase_date'], name='purchases_p_company_66a5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', 'payment_status'], name='purchases_p_supplie_e680f3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['invoice_no'], name='purchases_p_invoice_e05c39_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['is_active', 'payment_status'], name='purchases_p_is_acti_e9f7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_date', 'company'], name='purchases_p_purchas_34f3b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('company', 'invoice_no')},
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase', 'product'], name='purchases_p_purchas_00688d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['product', 'batch_no'], name='purchases_p_product_2cf55c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['expiry_date'], name='purchases_p_expiry__f5d71f_idx'),
        ),
    ]
