# Generated by Django 5.2.7 on 2025-10-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date', '-date_created']},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('digital', 'Digital Payment')], max_length=100, null=True),
        ),
    ]
