# Generated by Django 5.2.7 on 2025-11-12 14:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20251112_2007'),
        ('core', '0001_initial'),
        ('products', '0003_alter_companyproductsequence_last_number'),
        ('purchases', '0001_initial'),
        ('suppliers', '0002_alter_supplier_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('company', 'invoice_no')},
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['company', 'purchase_date'], name='purchases_p_company_66a5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', 'payment_status'], name='purchases_p_supplie_e680f3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['invoice_no'], name='purchases_p_invoice_e05c39_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase', 'product'], name='purchases_p_purchas_00688d_idx'),
        ),
    ]
