# Generated by Django 5.2.7 on 2025-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_supplier_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
