# Generated by Django 5.2.7 on 2025-10-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('purchases', '0002_alter_purchase_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
