# Generated by Django 5.2.7 on 2025-10-13 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_company'),
        ('core', '0001_initial'),
        ('products', '0001_initial'),
        ('purchases', '0003_purchase_account_purchase_payment_method'),
        ('sales', '0003_sale_account_sale_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('date', models.DateField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_stocks', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('return_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('return_charge_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='accounts.account')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='products.product')),
                ('purchase_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='purchases.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('return_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_type', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_charge_type', models.CharField(blank=True, max_length=50, null=True)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_returns', to='accounts.account')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.saleitem')),
            ],
        ),
    ]
