# Generated by Django 5.2.7 on 2025-12-16 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_can_manage_products'),
        ('products', '0001_initial'),
        ('purchases', '0002_purchase_expected_delivery_date_purchase_is_active_and_more'),
        ('returns', '0001_initial'),
        ('sales', '0002_alter_sale_customer_alter_saleitem_discount_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badstock',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ['-return_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='purchasereturnitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'ordering': ['-return_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='salesreturnitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='original_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='purchases.purchase'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='sales.sale'),
        ),
        migrations.AddIndex(
            model_name='badstock',
            index=models.Index(fields=['reference_type', 'reference_id'], name='returns_bad_referen_916767_idx'),
        ),
        migrations.AddIndex(
            model_name='badstock',
            index=models.Index(fields=['product', 'date'], name='returns_bad_product_366176_idx'),
        ),
    ]
