# Generated by Django 5.2.7 on 2026-01-25 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('returns', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='sales_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.salesreturn'),
        ),
        migrations.AddIndex(
            model_name='badstock',
            index=models.Index(fields=['reference_type', 'reference_id'], name='returns_bad_referen_916767_idx'),
        ),
        migrations.AddIndex(
            model_name='badstock',
            index=models.Index(fields=['product', 'date'], name='returns_bad_product_366176_idx'),
        ),
    ]
