# Generated by Django 5.2.7 on 2025-10-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badstock',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='purchasereturn',
            old_name='date',
            new_name='return_date',
        ),
        migrations.RenameField(
            model_name='purchasereturnitem',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='purchasereturnitem',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='salesreturn',
            old_name='invoice_no',
            new_name='receipt_no',
        ),
        migrations.RenameField(
            model_name='salesreturn',
            old_name='delivery_charge',
            new_name='return_amount',
        ),
        migrations.RenameField(
            model_name='salesreturn',
            old_name='discount',
            new_name='return_charge',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='purchase_ref',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='delivery_charge_type',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='service_charge',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='service_charge_type',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='vat_type',
        ),
        migrations.AddField(
            model_name='badstock',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badstock',
            name='reference_type',
            field=models.CharField(choices=[('sales_return', 'Sales Return'), ('purchase_return', 'Purchase Return'), ('direct', 'Direct')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='return_charge_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='damage_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_charge_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=50, null=True),
        ),
    ]
