# Generated by Django 5.2.7 on 2025-10-13 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('returns', '0002_remove_salesreturn_qty_remove_salesreturn_sale_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturn',
            name='product_ref',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='quantity',
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(blank=True, max_length=50, null=True)),
                ('product_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.purchasereturn')),
            ],
        ),
    ]
