# Generated by Django 5.2.7 on 2025-10-31 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_rename_qty_badstock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='return_date',
            field=models.DateField(),
        ),
    ]
