# Generated by Django 5.2.7 on 2026-01-25 07:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('ac_type', models.CharField(choices=[('Bank', 'Bank'), ('Mobile banking', 'Mobile banking'), ('Cash', 'Cash'), ('Other', 'Other')], default='Other', max_length=30)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('branch', models.CharField(blank=True, max_length=150, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ac_type__in', ['Bank', 'Mobile banking']), ('number__isnull', False)), fields=('company', 'ac_type', 'number'), name='unique_company_ac_type_number')],
            },
        ),
    ]
