# Generated by Django 5.2.7 on 2025-10-19 17:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ac_type', models.CharField(choices=[('Bank', 'Bank'), ('Mobile banking', 'Mobile banking'), ('Cash', 'Cash'), ('Other', 'Other')], default='Other', max_length=30)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('branch', models.CharField(blank=True, max_length=150, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
