# Generated by Django 5.2.7 on 2025-10-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'ac_type', 'number'), name='unique_company_ac_type_number'),
        ),
    ]
