# Generated by Django 5.2.7 on 2025-12-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_company_cash_account',
        ),
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_company_other_account',
        ),
    ]
