# Generated by Django 5.2.7 on 2025-11-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
    ]
