# Generated by Django 5.2.7 on 2025-10-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_active'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_company_ac_type_number',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('ac_type__in', ['Bank', 'Mobile banking']), ('number__isnull', False)), fields=('company', 'ac_type', 'number'), name='unique_company_ac_type_number'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('ac_type', 'Cash')), fields=('company', 'ac_type'), name='unique_company_cash_account'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('ac_type', 'Other')), fields=('company', 'ac_type'), name='unique_company_other_account'),
        ),
    ]
