# Generated by Django 5.2.7 on 2025-11-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_transactionitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionItem',
        ),
    ]
