# Generated by Django 5.2.7 on 2025-11-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20251112_2001'),
    ]

    operations = [
    ]
