# Generated by Django 5.2.7 on 2025-11-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fix_account_data'),
    ]

    operations = [
    ]
