# Generated by Django 5.2.7 on 2025-11-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='supplier_payment',
        ),
    ]
