# Generated by Django 5.2.7 on 2025-11-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
    ]
