# Generated by Django 5.2.7 on 2025-11-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
    ]
