# Generated by Django 5.2.7 on 2025-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_opening_balance',
            field=models.BooleanField(default=False),
        ),
    ]
