# Generated by Django 5.2.7 on 2025-11-20 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
        ('expenses', '0002_alter_expense_invoice_number'),
        ('money_receipts', '0003_alter_moneyreceipt_mr_no'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        ('supplier_payment', '0002_supplierpayment_account_and_more'),
        ('transactions', '0002_transaction_is_opening_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='supplier_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='supplier_payment.supplierpayment'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['supplier_payment'], name='transaction_supplie_0b03ae_idx'),
        ),
    ]
