# Generated by Django 5.2.7 on 2025-11-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_supplier_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
