# Generated by Django 5.2.7 on 2025-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_already_updated',
            field=models.BooleanField(default=False),
        ),
    ]
