# Generated by Django 5.2.7 on 2026-10-10 03:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rolepermission'),
        ('products', '0002_salemode_code_per_company'),
        ('sales', '0003_sale_tendered_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('stock_deducted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to='core.company')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_order', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shoporder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, help_text='Your shop address, e.g. shop.example.com (no https://). Leave empty if not used.', max_length=253, null=True, unique=True)),
                ('is_open', models.BooleanField(default=True, verbose_name='Accept orders')),
                ('shop_name', models.CharField(blank=True, help_text='Leave empty to use the company name.', max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('brand_color', models.CharField(default='#0f766e', help_text='Hex colour, e.g. #0f766e', max_length=7)),
                ('default_theme', models.CharField(choices=[('auto', "Follow the visitor's device"), ('light', 'Always light'), ('dark', 'Always dark')], default='auto', help_text='Visitors can still switch with the sun/moon button.', max_length=5)),
                ('announcement', models.CharField(blank=True, max_length=200, verbose_name='Top announcement')),
                ('hero_title', models.CharField(blank=True, max_length=120)),
                ('hero_subtitle', models.CharField(blank=True, max_length=240)),
                ('hero_button_text', models.CharField(default='Shop now', max_length=30)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='shop-banners/')),
                ('about_title', models.CharField(blank=True, max_length=80)),
                ('about_text', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, help_text='With country code, digits only.', max_length=30, verbose_name='WhatsApp number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('opening_hours', models.CharField(blank=True, max_length=120)),
                ('facebook_url', models.URLField(blank=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('free_delivery_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = no free delivery.', max_digits=10, verbose_name='Free delivery above')),
                ('delivery_note', models.CharField(blank=True, default='Delivery within 1–3 days', max_length=140)),
                ('payment_note', models.CharField(blank=True, default='Cash on delivery', max_length=140)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_settings', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Shop settings',
            },
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['company', 'status'], name='shop_shopor_company_50071c_idx'),
        ),
    ]
