# Generated by Django 5.2.7 on 2026-01-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='special_customer',
            field=models.BooleanField(default=False),
        ),
    ]
