# Generated by Django 6.0.2 on 2026-02-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Banking'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=100),
        ),
    ]
