# Generated by Django 5.2.7 on 2025-12-03 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_account_unique_company_cash_account_and_more'),
        ('core', '0003_user_can_manage_products'),
        ('transactions', '0004_transaction_date_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('transfer_type', models.CharField(choices=[('internal', 'Internal Transfer'), ('external', 'External Transfer'), ('adjustment', 'Balance Adjustment')], default='internal', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_credits', to='transactions.transaction')),
                ('debit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_debits', to='transactions.transaction')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='accounts.account')),
                ('original_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='account_transfer.accounttransfer')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='accounts.account')),
            ],
            options={
                'ordering': ['-transfer_date', '-id'],
                'indexes': [models.Index(fields=['company', 'transfer_date'], name='account_tra_company_b9b4ac_idx'), models.Index(fields=['from_account', 'transfer_date'], name='account_tra_from_ac_7a013c_idx'), models.Index(fields=['to_account', 'transfer_date'], name='account_tra_to_acco_d035be_idx'), models.Index(fields=['transfer_no'], name='account_tra_transfe_636cb1_idx'), models.Index(fields=['status'], name='account_tra_status_ce64c5_idx')],
            },
        ),
    ]
