# Generated by Django 5.2.7 on 2026-01-25 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_transfer', '0001_initial'),
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransfer',
            name='credit_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_for_transfer', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='accounttransfer',
            name='debit_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_for_transfer', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='accounttransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='accounttransfer',
            name='original_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='account_transfer.accounttransfer'),
        ),
        migrations.AddField(
            model_name='accounttransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='accounts.account'),
        ),
        migrations.AddIndex(
            model_name='accounttransfer',
            index=models.Index(fields=['company', 'transfer_date'], name='account_tra_company_b9b4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransfer',
            index=models.Index(fields=['from_account', 'transfer_date'], name='account_tra_from_ac_7a013c_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransfer',
            index=models.Index(fields=['to_account', 'transfer_date'], name='account_tra_to_acco_d035be_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransfer',
            index=models.Index(fields=['transfer_no'], name='account_tra_transfe_636cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransfer',
            index=models.Index(fields=['status'], name='account_tra_status_ce64c5_idx'),
        ),
    ]
