# Generated by Django 5.2.7 on 2025-12-03 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_transfer', '0001_initial'),
        ('transactions', '0004_transaction_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransfer',
            name='credit_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_credit', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='accounttransfer',
            name='debit_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_debit', to='transactions.transaction'),
        ),
    ]
