# Generated by Django 5.2.7 on 2025-12-03 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_transfer', '0002_alter_accounttransfer_credit_transaction_and_more'),
        ('transactions', '0005_transaction_balance_already_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransfer',
            name='credit_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_for_transfer', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='accounttransfer',
            name='debit_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_for_transfer', to='transactions.transaction'),
        ),
    ]
