# Generated by Django 5.2.7 on 2025-10-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneyreceipt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='moneyreceipt',
            name='payment_type',
            field=models.CharField(choices=[('overall', 'Overall Payment'), ('specific', 'Specific Invoice Payment')], default='overall', max_length=20),
        ),
        migrations.AddField(
            model_name='moneyreceipt',
            name='specific_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
