# Generated by Django 5.2.7 on 2025-11-14 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('money_receipts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyreceipt',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_money_receipt', to='transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='moneyreceipt',
            index=models.Index(fields=['company', 'payment_date'], name='money_recei_company_c9b2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='moneyreceipt',
            index=models.Index(fields=['customer', 'payment_date'], name='money_recei_custome_418bac_idx'),
        ),
        migrations.AddIndex(
            model_name='moneyreceipt',
            index=models.Index(fields=['mr_no'], name='money_recei_mr_no_619b60_idx'),
        ),
        migrations.AddIndex(
            model_name='moneyreceipt',
            index=models.Index(fields=['is_advance_payment'], name='money_recei_is_adva_3aa88d_idx'),
        ),
        migrations.AddIndex(
            model_name='moneyreceipt',
            index=models.Index(fields=['is_due_payment'], name='money_recei_is_due__38ae63_idx'),
        ),
    ]
