# Generated by Django 5.2.7 on 2025-11-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_receipts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyreceipt',
            name='mr_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
