# Generated by Django 5.2.7 on 2025-11-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_receipts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moneyreceipt',
            name='money_recei_is_due__38ae63_idx',
        ),
        migrations.RemoveField(
            model_name='moneyreceipt',
            name='advance_balance',
        ),
        migrations.RemoveField(
            model_name='moneyreceipt',
            name='due_invoice_no',
        ),
        migrations.RemoveField(
            model_name='moneyreceipt',
            name='is_due_payment',
        ),
        migrations.AlterField(
            model_name='moneyreceipt',
            name='payment_type',
            field=models.CharField(choices=[('overall', 'Overall Payment'), ('specific', 'Specific Invoice Payment'), ('advance', 'Advance Payment')], default='overall', max_length=20),
        ),
    ]
