# Generated by Django 5.2.7 on 2025-12-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_receipts', '0003_alter_moneyreceipt_mr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyreceipt',
            name='sale_invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moneyreceipt',
            name='mr_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
