# Generated by Django 5.2.7 on 2026-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_receipts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyreceipt',
            name='allocation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
