# Generated by Django 5.2.7 on 2025-11-20 16:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
        ('purchases', '0001_initial'),
        ('supplier_payment', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('transactions', '0002_transaction_is_opening_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='advance_amount_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_type',
            field=models.CharField(choices=[('specific', 'Specific Bill Payment'), ('overall', 'Overall Payment'), ('advance', 'Advance Payment')], default='overall', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='purchases.purchase'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='sp_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_supplier_payment', to='transactions.transaction', unique=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='use_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['company', 'payment_date'], name='supplier_pa_company_5e472c_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'payment_date'], name='supplier_pa_supplie_99cb10_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['sp_no'], name='supplier_pa_sp_no_a19358_idx'),
        ),
    ]
