# Generated by Django 5.2.7 on 2025-11-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payment', '0001_initial'),
        ('transactions', '0002_remove_transaction_supplier_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierPayment',
        ),
    ]
