# Generated by Django 5.2.7 on 2025-11-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('digital', 'Digital Payment'), ('mobile banking', 'Mobile Banking')], default='cash', max_length=20),
        ),
    ]
