# Generated by Django 5.2.7 on 2025-11-14 17:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='specific_bill',
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='advance_amount_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='use_advance',
            field=models.BooleanField(default=False, help_text="Use supplier's advance balance for payment"),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('digital', 'Digital Payment'), ('mobile_banking', 'Mobile Banking')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_type',
            field=models.CharField(choices=[('overall', 'Overall Payment'), ('specific', 'Specific Bill Payment'), ('advance', 'Advance Payment')], default='overall', max_length=20),
        ),
    ]
