# Generated by Django 5.2.7 on 2026-01-25 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_payment', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['company', 'payment_date'], name='supplier_pa_company_5e472c_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'payment_date'], name='supplier_pa_supplie_99cb10_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['sp_no'], name='supplier_pa_sp_no_a19358_idx'),
        ),
    ]
