# Generated by Django 5.2.7 on 2025-11-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payment', '0002_alter_supplierpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='sp_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
