# Generated by Django 5.2.7 on 2025-11-20 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payment', '0003_alter_supplierpayment_sp_no_and_more'),
        ('transactions', '0003_transaction_supplier_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='sp_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payment_link', to='transactions.transaction'),
        ),
    ]
