# Generated by Django 5.2.7 on 2025-11-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payment', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierPayment',
        ),
    ]
