# Generated by Django 5.2.7 on 2025-11-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payment', '0004_alter_supplierpayment_sp_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
    ]
