# Generated by Django 5.2.7 on 2025-10-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Walk-in Customer', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=20)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('sale_by', models.CharField(blank=True, max_length=100, null=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overall_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overall_discount_type', models.CharField(blank=True, max_length=20, null=True)),
                ('overall_delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overall_delivery_charge_type', models.CharField(blank=True, max_length=20, null=True)),
                ('overall_service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overall_vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overall_vat_type', models.CharField(blank=True, max_length=20, null=True)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('cheque', 'Cheque'), ('mobile', 'Mobile')], default='cash', max_length=20)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sales', to='sales.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(blank=True, max_length=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
