# Generated by Django 5.2.7 on 2025-12-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], default='fixed', max_length=10),
        ),
    ]
