# Generated by Django 5.2.7 on 2025-11-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_payment_f41ab8_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_due_dat_626ea7_idx',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='advance_available',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='advance_payments',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='advance_used',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_overdue',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sale',
            name='with_money_receipt',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
