# Generated by Django 5.2.7 on 2025-10-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='change_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='overall_delivery_charge_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='overall_vat_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_by',
        ),
    ]
