# Generated by Django 5.2.7 on 2025-10-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_unique_company_ac_type_number'),
        ('sales', '0002_alter_sale_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_type',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('saved_customer', 'Saved Customer')], default='walk_in', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='sale',
            name='with_money_receipt',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
