# Generated by Django 5.2.7 on 2026-10-06 09:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_updated_at_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tendered_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
