# Generated by Django 5.2.7 on 2026-01-23 14:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_salemode_productsalemode_pricetier_and_more'),
        ('sales', '0002_alter_sale_customer_alter_saleitem_discount_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['id'], 'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='base_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.00'), help_text='Quantity converted to base unit', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='flat_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_type',
            field=models.CharField(choices=[('unit', 'Unit Price'), ('flat', 'Flat Price'), ('tier', 'Tier Price')], default='unit', max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale_mode',
            field=models.ForeignKey(blank=True, help_text='Sale mode used for this item (KG, GRAM, BOSTA, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.salemode'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.00'), help_text='Quantity in sale mode unit (e.g., 2 BOSTA, 3 DOZEN)', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
