# Generated by Django 5.2.7 on 2026-01-24 06:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_unit_alter_productsalemode_product_and_more'),
        ('sales', '0003_alter_saleitem_options_remove_saleitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_quantity',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.00'), help_text='Quantity (acts as sale_quantity for compatibility)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price_type',
            field=models.CharField(choices=[('unit', 'Unit Price'), ('flat', 'Flat Price'), ('tier', 'Tier Price'), ('normal', 'Normal Price')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_mode',
            field=models.ForeignKey(blank=True, help_text='Sale mode used for this item (KG, GRAM, BOSTA, etc.) - Optional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.salemode'),
        ),
    ]
