# Generated by Django 5.2.7 on 2025-10-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_due_amount_sale_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='overall_delivery_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='overall_discount_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='overall_service_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='overall_vat_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
