# Generated by Django 5.2.7 on 2026-10-06 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rolepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(unique=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('platform', models.CharField(blank=True, default='', max_length=30)),
                ('app_version', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_pull_cursor', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='sync_devices', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_devices', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SyncIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.UUIDField(db_index=True)),
                ('entity', models.CharField(blank=True, default='', max_length=40)),
                ('issue_type', models.CharField(choices=[('stock_conflict', 'Stock conflict'), ('rejected', 'Rejected')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('client_time', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution', models.CharField(blank=True, default='', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offline_sync.device')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display', models.CharField(blank=True, default='', max_length=150)),
                ('source', models.CharField(default='api', max_length=20)),
                ('model_label', models.CharField(db_index=True, max_length=80)),
                ('entity', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=200)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('client_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offline_sync.device')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'id'], name='offline_syn_company_8474db_idx'), models.Index(fields=['company', 'model_label', 'object_id'], name='offline_syn_company_8cf1a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.UUIDField(unique=True)),
                ('entity', models.CharField(blank=True, default='', max_length=40)),
                ('method', models.CharField(default='POST', max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('local_id', models.BigIntegerField(blank=True, null=True)),
                ('server_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('stock_conflict', 'Stock conflict'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('client_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offline_sync.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'entity', 'local_id'], name='offline_syn_device__420eac_idx')],
            },
        ),
    ]
