# Generated by Django 5.2.7 on 2026-01-23 14:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_fiscal_year_start'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='KG, GRAM, PACKET, BOSTA, DOZEN, etc.', max_length=50)),
                ('code', models.CharField(help_text='Unique code for mode', max_length=20, unique=True)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=Decimal('1.00'), help_text='Multiplier to convert to base unit (e.g., 0.001 for GRAM to KG)', max_digits=12)),
                ('price_type', models.CharField(choices=[('unit', 'Unit Price'), ('flat', 'Flat Price'), ('tier', 'Tier Price')], default='unit', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_modes', to='products.unit')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSaleMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('flat_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=10, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_modes', to='products.product')),
                ('sale_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.salemode')),
            ],
            options={
                'ordering': ['sale_mode__name'],
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=3, help_text='Minimum quantity (in base unit) for this tier', max_digits=12)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Maximum quantity (in base unit) for this tier (null for unlimited)', max_digits=12, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_sale_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='products.productsalemode')),
            ],
            options={
                'ordering': ['min_quantity'],
                'constraints': [models.UniqueConstraint(fields=('product_sale_mode', 'min_quantity'), name='unique_tier_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='salemode',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_sale_mode_per_company'),
        ),
        migrations.AddConstraint(
            model_name='productsalemode',
            constraint=models.UniqueConstraint(fields=('product', 'sale_mode'), name='unique_product_sale_mode'),
        ),
    ]
