# Generated by Django 5.2.7 on 2026-10-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salemode",
            name="code",
            field=models.CharField(
                help_text="Short code, unique within the company", max_length=20
            ),
        ),
    ]
