# Generated by Django 5.2.7 on 2025-10-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_sub_name',
        ),
    ]
