# Generated by Django 5.2.7 on 2026-01-23 15:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_salemode_productsalemode_pricetier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salemode',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='salemode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salemode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sale_modes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salemode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
