# Generated by Django 5.2.7 on 2025-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproductsequence',
            name='last_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
