# Generated by Django 5.2.7 on 2026-01-24 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_salemode_options_salemode_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.unit'),
        ),
        migrations.AlterField(
            model_name='productsalemode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale_modes', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productsalemode',
            name='sale_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale_modes', to='products.salemode'),
        ),
    ]
