# Generated by Django 5.2.7 on 2025-11-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_companyproductsequence_last_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproductsequence',
            name='last_number',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
