# Generated by Django 5.2.7 on 2026-01-24 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_unit_alter_productsalemode_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricetier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
