# Generated by Django 5.2.7 on 2025-10-19 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_company_alter_user_role'),
        ('products', '0005_brand_created_by_category_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProductSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_sequence', to='core.company')),
            ],
        ),
    ]
