from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('sales/', views.sales_list_view, name='sales'),
    path('sales/new/', views.sale_new_view, name='sale_new'),
    path('pos/', views.pos_view, name='pos'),
    path('money-receipts/', views.receipts_list_view, name='receipts'),
    path('money-receipts/new/', views.receipt_create_view, name='receipt_new'),
    path('purchases/', views.purchases_list_view, name='purchases'),
    path('purchases/new/', views.purchase_create_view, name='purchase_new'),
    path('suppliers/', views.suppliers_view, name='suppliers'),
    path('customers/', views.customers_view, name='customers'),
    path('products/', views.products_view, name='products'),
    path('accounts/', views.accounts_view, name='accounts'),
    path('units/', views.units_view, name='units'),
    path('categories/', views.categories_view, name='categories'),
    path('brands/', views.brands_view, name='brands'),
    path('groups/', views.groups_view, name='groups'),
    path('sources/', views.sources_view, name='sources'),
    path('sale-modes/', views.sale_modes_view, name='sale_modes'),
    path('expenses/', views.expenses_view, name='expenses'),
    path('expense-heads/', views.expense_heads_view, name='expense_heads'),
    path('expense-subheads/', views.expense_subheads_view, name='expense_subheads'),
    path('income/', views.incomes_view, name='incomes'),
    path('income-heads/', views.income_heads_view, name='income_heads'),
    path('staff/', views.staff_view, name='staff'),
    path('company-profile/', views.company_profile_view, name='company_profile'),
    path('user-permissions/', views.user_permissions_view, name='user_permissions'),
    path('platform/companies/', views.platform_companies_view, name='platform_companies'),
    path('supplier-payments/', views.supplier_payments_view, name='supplier_payments'),
    path('supplier-payments/new/', views.supplier_payment_new_view, name='supplier_pay'),
    path('sales-returns/', views.sales_returns_view, name='sales_returns'),
    path('sales-returns/new/', views.sales_return_new_view, name='sales_return_new'),
    path('purchase-returns/', views.purchase_returns_view, name='purchase_returns'),
    path('purchase-returns/new/', views.purchase_return_new_view, name='purchase_return_new'),
    path('bad-stock/', views.bad_stock_view, name='bad_stock'),
    path('transfers/', views.transfers_view, name='transfers'),
    path('transfers/new/', views.transfer_new_view, name='transfer_new'),
    path('transactions/', views.transactions_view, name='transactions'),
    path('audit-log/', views.audit_log_view, name='audit_log'),
    path('m/<slug:slug>/', views.soon_view, name='soon'),
]
